# Generated by Django 5.1.4 on 2024-12-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='milk_preference',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sugar_level',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
    ]
